package game

import (
	"fmt"
	"sort"
	"strings"

	"dmud/internal/components"
)

// GenerateDocs renders the game's content registries (classes, spells, races,
// consumables) into markdown, keyed by repo-relative path. It is the single
// source of truth → human-readable views pipeline: `make docs` writes these and
// a golden test fails if the committed files drift. Output is deterministic.
func GenerateDocs() map[string]string {
	return map[string]string{
		"docs/README.md":      genIndex(),
		"docs/classes.md":     genClasses(),
		"docs/spells.md":      genSpells(),
		"docs/races.md":       genRaces(),
		"docs/forms.md":       genForms(),
		"docs/consumables.md": genConsumables(),
	}
}

const docHeader = "<!-- GENERATED by `make docs` from the game registries. Do not edit by hand. -->\n\n"

func genIndex() string {
	var b strings.Builder
	b.WriteString(docHeader)
	b.WriteString("# Game Content\n\n")
	b.WriteString("Generated from the code registries — always current. Run `make docs` after changing content.\n\n")
	b.WriteString("- [Classes](classes.md) — character classes and the schools they draw from\n")
	b.WriteString("- [Spells](spells.md) — every spell, by school\n")
	b.WriteString("- [Races](races.md) — stat offsets and size\n")
	b.WriteString("- [Forms](forms.md) — Druid shapeshift beast forms\n")
	b.WriteString("- [Consumables](consumables.md) — food and potions\n\n")
	b.WriteString("For design intent and balance philosophy (the *why*), see [GAME_DESIGN.md](../GAME_DESIGN.md).\n")
	return b.String()
}

// allSchools returns the spell schools present, sorted.
func allSchools() []string {
	seen := map[string]bool{}
	for _, def := range spellRegistry {
		if def.School != "" {
			seen[def.School] = true
		}
	}
	out := make([]string, 0, len(seen))
	for s := range seen {
		out = append(out, s)
	}
	sort.Strings(out)
	return out
}

func spellRows(b *strings.Builder, defs []*SpellDefinition) {
	b.WriteString("| Spell | Lvl | EP | Effect |\n|---|---|---|---|\n")
	for _, d := range defs {
		lvl := d.MinLevel
		if lvl < 1 {
			lvl = 1
		}
		effect := d.Power
		if effect == "" {
			effect = d.Description
		}
		b.WriteString(fmt.Sprintf("| %s | %d | %d | %s |\n", d.Name, lvl, d.Cost, effect))
	}
}

func genSpells() string {
	var b strings.Builder
	b.WriteString(docHeader)
	b.WriteString("# Spells\n\n")
	for _, school := range allSchools() {
		b.WriteString("## " + title(school) + "\n\n")
		spellRows(&b, spellsInSchool(school))
		b.WriteString("\n")
	}
	return b.String()
}

func genClasses() string {
	var b strings.Builder
	b.WriteString(docHeader)
	b.WriteString("# Classes\n\n")
	for _, c := range classRegistry {
		b.WriteString("## " + c.Name + "\n\n")
		b.WriteString(c.Description + "\n\n")
		b.WriteString(fmt.Sprintf("- **Primary stat:** %s\n", components.StatName(c.PrimaryStat)))
		b.WriteString(fmt.Sprintf("- **Schools:** %s\n", strings.Join(mapTitle(c.Schools), ", ")))
		if len(c.Abilities) > 0 {
			b.WriteString(fmt.Sprintf("- **Abilities:** %s\n", strings.Join(mapTitle(c.Abilities), ", ")))
		}
		b.WriteString("\n")
		var defs []*SpellDefinition
		for _, s := range c.Schools {
			defs = append(defs, spellsInSchool(s)...)
		}
		spellRows(&b, defs)
		b.WriteString("\n")
	}
	return b.String()
}

func genRaces() string {
	var b strings.Builder
	b.WriteString(docHeader)
	b.WriteString("# Races\n\n")
	b.WriteString("Offsets are applied to the base stat value of 10.\n\n")
	b.WriteString("| Race | Size | STR | DEX | CON | INT | WIS |\n|---|---|---|---|---|---|---|\n")
	for _, key := range components.RaceNames() {
		def, ok := components.RaceFor(key)
		if !ok {
			continue
		}
		cells := []string{def.Name, def.Size.String()}
		for _, t := range components.AllStats() {
			cells = append(cells, modStr(def.StatMods[t]))
		}
		b.WriteString("| " + strings.Join(cells, " | ") + " |\n")
	}
	return b.String()
}

func genForms() string {
	var b strings.Builder
	b.WriteString(docHeader)
	b.WriteString("# Shapeshift Forms\n\n")
	b.WriteString("The Druid's `shift <form>` beast shapes. While shifted you fight in melee with the form's natural weapons (×STR) and **cannot cast** — `revert` to your own shape to use magic.\n\n")
	b.WriteString("| Form | Lvl | Melee | Description |\n|---|---|---|---|\n")
	for _, key := range components.FormNames() {
		f, ok := components.FormFor(key)
		if !ok {
			continue
		}
		b.WriteString(fmt.Sprintf("| %s | %d | %d–%d | %s |\n", f.Label, f.MinLevel, f.MinDamage, f.MaxDamage, f.Description))
	}
	return b.String()
}

func genConsumables() string {
	var b strings.Builder
	b.WriteString(docHeader)
	b.WriteString("# Consumables\n\n")
	b.WriteString("Eat / drink / quaff to restore. Brand-new characters start with a few.\n\n")
	b.WriteString("| Item | Restores |\n|---|---|\n")

	ids := make([]string, 0, len(components.ConsumableRegistry))
	for id := range components.ConsumableRegistry {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	for _, id := range ids {
		eff := components.ConsumableRegistry[id]
		name := id
		if tmpl, ok := components.ItemTemplates[id]; ok {
			name = tmpl.Name
		}
		var parts []string
		if eff.RestoreHP > 0 {
			parts = append(parts, fmt.Sprintf("+%d HP", eff.RestoreHP))
		}
		if eff.RestoreEP > 0 {
			parts = append(parts, fmt.Sprintf("+%d endurance", eff.RestoreEP))
		}
		b.WriteString(fmt.Sprintf("| %s | %s |\n", name, strings.Join(parts, ", ")))
	}
	return b.String()
}

// --- small helpers ---

func modStr(v int) string {
	if v == 0 {
		return "–"
	}
	return fmt.Sprintf("%+d", v)
}

func title(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

func mapTitle(ss []string) []string {
	out := make([]string, len(ss))
	for i, s := range ss {
		out[i] = title(s)
	}
	return out
}
